export const LOGIN_INIT = 'LOGIN_INIT'
export const SET_USER = 'SET_USER'
export const SET_TOKEN = 'SET_TOKEN'
export const LOGIN_OUT = 'LOGIN_OUT'
export const SET_MENU = 'SET_MENU'
export const SET_BTNLIST = 'SET_BTNLIST'
export const SET_PAGELIST = 'SET_PAGELIST'
export const Freight_List = 'Freight_List'